// NOTE: this file has been automatically generated by blendef for Blender v400.

package v400

import (
	"encoding/binary"
	"io"

	. "github.com/mewspring/blend/block/generic"
)

// ParseStructure parses a structure from based on its name
func ParseStructure(r io.Reader, order binary.ByteOrder, ptrSize int, typ string, count uint32) (body any, err error) {
	switch typ {
	case "ARegion":
		body, err = ReadT[ARegion](r, order, ptrSize, count)
	case "ARegion_Runtime":
		body, err = ReadT[ARegion_Runtime](r, order, ptrSize, count)
	case "AnimData":
		body, err = ReadT[AnimData](r, order, ptrSize, count)
	case "AnimOverride":
		body, err = ReadT[AnimOverride](r, order, ptrSize, count)
	case "ArmatureGpencilModifierData":
		body, err = ReadT[ArmatureGpencilModifierData](r, order, ptrSize, count)
	case "ArmatureModifierData":
		body, err = ReadT[ArmatureModifierData](r, order, ptrSize, count)
	case "ArrayGpencilModifierData":
		body, err = ReadT[ArrayGpencilModifierData](r, order, ptrSize, count)
	case "ArrayModifierData":
		body, err = ReadT[ArrayModifierData](r, order, ptrSize, count)
	case "AssetLibraryReference":
		body, err = ReadT[AssetLibraryReference](r, order, ptrSize, count)
	case "AssetMetaData":
		body, err = ReadT[AssetMetaData](r, order, ptrSize, count)
	case "AssetShelf":
		body, err = ReadT[AssetShelf](r, order, ptrSize, count)
	case "AssetShelfSettings":
		body, err = ReadT[AssetShelfSettings](r, order, ptrSize, count)
	case "AssetTag":
		body, err = ReadT[AssetTag](r, order, ptrSize, count)
	case "AssetWeakReference":
		body, err = ReadT[AssetWeakReference](r, order, ptrSize, count)
	case "AudioData":
		body, err = ReadT[AudioData](r, order, ptrSize, count)
	case "AviCodecData":
		body, err = ReadT[AviCodecData](r, order, ptrSize, count)
	case "BPoint":
		body, err = ReadT[BPoint](r, order, ptrSize, count)
	case "BakeData":
		body, err = ReadT[BakeData](r, order, ptrSize, count)
	case "Base":
		body, err = ReadT[Base](r, order, ptrSize, count)
	case "BevelModifierData":
		body, err = ReadT[BevelModifierData](r, order, ptrSize, count)
	case "BezTriple":
		body, err = ReadT[BezTriple](r, order, ptrSize, count)
	case "BlurShaderFxData":
		body, err = ReadT[BlurShaderFxData](r, order, ptrSize, count)
	case "BoidData":
		body, err = ReadT[BoidData](r, order, ptrSize, count)
	case "BoidParticle":
		body, err = ReadT[BoidParticle](r, order, ptrSize, count)
	case "BoidRule":
		body, err = ReadT[BoidRule](r, order, ptrSize, count)
	case "BoidRuleAverageSpeed":
		body, err = ReadT[BoidRuleAverageSpeed](r, order, ptrSize, count)
	case "BoidRuleAvoidCollision":
		body, err = ReadT[BoidRuleAvoidCollision](r, order, ptrSize, count)
	case "BoidRuleFight":
		body, err = ReadT[BoidRuleFight](r, order, ptrSize, count)
	case "BoidRuleFollowLeader":
		body, err = ReadT[BoidRuleFollowLeader](r, order, ptrSize, count)
	case "BoidRuleGoalAvoid":
		body, err = ReadT[BoidRuleGoalAvoid](r, order, ptrSize, count)
	case "BoidSettings":
		body, err = ReadT[BoidSettings](r, order, ptrSize, count)
	case "BoidState":
		body, err = ReadT[BoidState](r, order, ptrSize, count)
	case "Bone":
		body, err = ReadT[Bone](r, order, ptrSize, count)
	case "BoneCollection":
		body, err = ReadT[BoneCollection](r, order, ptrSize, count)
	case "BoneCollectionMember":
		body, err = ReadT[BoneCollectionMember](r, order, ptrSize, count)
	case "BoneCollectionReference":
		body, err = ReadT[BoneCollectionReference](r, order, ptrSize, count)
	case "BoneColor":
		body, err = ReadT[BoneColor](r, order, ptrSize, count)
	case "Bone_Runtime":
		body, err = ReadT[Bone_Runtime](r, order, ptrSize, count)
	case "BooleanModifierData":
		body, err = ReadT[BooleanModifierData](r, order, ptrSize, count)
	case "BoundBox":
		body, err = ReadT[BoundBox](r, order, ptrSize, count)
	case "BrightContrastModifierData":
		body, err = ReadT[BrightContrastModifierData](r, order, ptrSize, count)
	case "Brush":
		body, err = ReadT[Brush](r, order, ptrSize, count)
	case "BrushClone":
		body, err = ReadT[BrushClone](r, order, ptrSize, count)
	case "BrushCurvesSculptSettings":
		body, err = ReadT[BrushCurvesSculptSettings](r, order, ptrSize, count)
	case "BrushGpencilSettings":
		body, err = ReadT[BrushGpencilSettings](r, order, ptrSize, count)
	case "BuildEff":
		body, err = ReadT[BuildEff](r, order, ptrSize, count)
	case "BuildGpencilModifierData":
		body, err = ReadT[BuildGpencilModifierData](r, order, ptrSize, count)
	case "BuildModifierData":
		body, err = ReadT[BuildModifierData](r, order, ptrSize, count)
	case "CBData":
		body, err = ReadT[CBData](r, order, ptrSize, count)
	case "CacheFile":
		body, err = ReadT[CacheFile](r, order, ptrSize, count)
	case "CacheFileLayer":
		body, err = ReadT[CacheFileLayer](r, order, ptrSize, count)
	case "CacheObjectPath":
		body, err = ReadT[CacheObjectPath](r, order, ptrSize, count)
	case "Camera":
		body, err = ReadT[Camera](r, order, ptrSize, count)
	case "CameraBGImage":
		body, err = ReadT[CameraBGImage](r, order, ptrSize, count)
	case "CameraDOFSettings":
		body, err = ReadT[CameraDOFSettings](r, order, ptrSize, count)
	case "CameraStereoSettings":
		body, err = ReadT[CameraStereoSettings](r, order, ptrSize, count)
	case "Camera_Runtime":
		body, err = ReadT[Camera_Runtime](r, order, ptrSize, count)
	case "CastModifierData":
		body, err = ReadT[CastModifierData](r, order, ptrSize, count)
	case "ChannelDriver":
		body, err = ReadT[ChannelDriver](r, order, ptrSize, count)
	case "CharInfo":
		body, err = ReadT[CharInfo](r, order, ptrSize, count)
	case "ChildParticle":
		body, err = ReadT[ChildParticle](r, order, ptrSize, count)
	case "ClothCollSettings":
		body, err = ReadT[ClothCollSettings](r, order, ptrSize, count)
	case "ClothModifierData":
		body, err = ReadT[ClothModifierData](r, order, ptrSize, count)
	case "ClothSimSettings":
		body, err = ReadT[ClothSimSettings](r, order, ptrSize, count)
	case "Collection":
		body, err = ReadT[Collection](r, order, ptrSize, count)
	case "CollectionChild":
		body, err = ReadT[CollectionChild](r, order, ptrSize, count)
	case "CollectionLightLinking":
		body, err = ReadT[CollectionLightLinking](r, order, ptrSize, count)
	case "CollectionObject":
		body, err = ReadT[CollectionObject](r, order, ptrSize, count)
	case "Collection_Runtime":
		body, err = ReadT[Collection_Runtime](r, order, ptrSize, count)
	case "CollisionModifierData":
		body, err = ReadT[CollisionModifierData](r, order, ptrSize, count)
	case "ColorBalanceModifierData":
		body, err = ReadT[ColorBalanceModifierData](r, order, ptrSize, count)
	case "ColorBand":
		body, err = ReadT[ColorBand](r, order, ptrSize, count)
	case "ColorCorrectionData":
		body, err = ReadT[ColorCorrectionData](r, order, ptrSize, count)
	case "ColorGpencilModifierData":
		body, err = ReadT[ColorGpencilModifierData](r, order, ptrSize, count)
	case "ColorManagedColorspaceSettings":
		body, err = ReadT[ColorManagedColorspaceSettings](r, order, ptrSize, count)
	case "ColorManagedDisplaySettings":
		body, err = ReadT[ColorManagedDisplaySettings](r, order, ptrSize, count)
	case "ColorManagedViewSettings":
		body, err = ReadT[ColorManagedViewSettings](r, order, ptrSize, count)
	case "ColorMapping":
		body, err = ReadT[ColorMapping](r, order, ptrSize, count)
	case "ColorMixVars":
		body, err = ReadT[ColorMixVars](r, order, ptrSize, count)
	case "ColorizeShaderFxData":
		body, err = ReadT[ColorizeShaderFxData](r, order, ptrSize, count)
	case "ConsoleLine":
		body, err = ReadT[ConsoleLine](r, order, ptrSize, count)
	case "CorrectiveSmoothDeltaCache":
		body, err = ReadT[CorrectiveSmoothDeltaCache](r, order, ptrSize, count)
	case "CorrectiveSmoothModifierData":
		body, err = ReadT[CorrectiveSmoothModifierData](r, order, ptrSize, count)
	case "CryptomatteEntry":
		body, err = ReadT[CryptomatteEntry](r, order, ptrSize, count)
	case "CryptomatteLayer":
		body, err = ReadT[CryptomatteLayer](r, order, ptrSize, count)
	case "Curve":
		body, err = ReadT[Curve](r, order, ptrSize, count)
	case "CurveMap":
		body, err = ReadT[CurveMap](r, order, ptrSize, count)
	case "CurveMapPoint":
		body, err = ReadT[CurveMapPoint](r, order, ptrSize, count)
	case "CurveMapping":
		body, err = ReadT[CurveMapping](r, order, ptrSize, count)
	case "CurveModifierData":
		body, err = ReadT[CurveModifierData](r, order, ptrSize, count)
	case "CurvePaintSettings":
		body, err = ReadT[CurvePaintSettings](r, order, ptrSize, count)
	case "CurveProfile":
		body, err = ReadT[CurveProfile](r, order, ptrSize, count)
	case "CurveProfilePoint":
		body, err = ReadT[CurveProfilePoint](r, order, ptrSize, count)
	case "Curves":
		body, err = ReadT[Curves](r, order, ptrSize, count)
	case "CurvesGeometry":
		body, err = ReadT[CurvesGeometry](r, order, ptrSize, count)
	case "CurvesModifierData":
		body, err = ReadT[CurvesModifierData](r, order, ptrSize, count)
	case "CurvesSculpt":
		body, err = ReadT[CurvesSculpt](r, order, ptrSize, count)
	case "CustomData":
		body, err = ReadT[CustomData](r, order, ptrSize, count)
	case "CustomDataExternal":
		body, err = ReadT[CustomDataExternal](r, order, ptrSize, count)
	case "CustomDataLayer":
		body, err = ReadT[CustomDataLayer](r, order, ptrSize, count)
	case "CustomData_MeshMasks":
		body, err = ReadT[CustomData_MeshMasks](r, order, ptrSize, count)
	case "DashGpencilModifierData":
		body, err = ReadT[DashGpencilModifierData](r, order, ptrSize, count)
	case "DashGpencilModifierSegment":
		body, err = ReadT[DashGpencilModifierSegment](r, order, ptrSize, count)
	case "DataTransferModifierData":
		body, err = ReadT[DataTransferModifierData](r, order, ptrSize, count)
	case "DecimateModifierData":
		body, err = ReadT[DecimateModifierData](r, order, ptrSize, count)
	case "DisplaceModifierData":
		body, err = ReadT[DisplaceModifierData](r, order, ptrSize, count)
	case "DisplaySafeAreas":
		body, err = ReadT[DisplaySafeAreas](r, order, ptrSize, count)
	case "DrawDataList":
		body, err = ReadT[DrawDataList](r, order, ptrSize, count)
	case "DriverTarget":
		body, err = ReadT[DriverTarget](r, order, ptrSize, count)
	case "DriverVar":
		body, err = ReadT[DriverVar](r, order, ptrSize, count)
	case "DualQuat":
		body, err = ReadT[DualQuat](r, order, ptrSize, count)
	case "DynamicPaintBrushSettings":
		body, err = ReadT[DynamicPaintBrushSettings](r, order, ptrSize, count)
	case "DynamicPaintCanvasSettings":
		body, err = ReadT[DynamicPaintCanvasSettings](r, order, ptrSize, count)
	case "DynamicPaintModifierData":
		body, err = ReadT[DynamicPaintModifierData](r, order, ptrSize, count)
	case "DynamicPaintSurface":
		body, err = ReadT[DynamicPaintSurface](r, order, ptrSize, count)
	case "EQCurveMappingData":
		body, err = ReadT[EQCurveMappingData](r, order, ptrSize, count)
	case "EdgeSplitModifierData":
		body, err = ReadT[EdgeSplitModifierData](r, order, ptrSize, count)
	case "Editing":
		body, err = ReadT[Editing](r, order, ptrSize, count)
	case "EditingRuntime":
		body, err = ReadT[EditingRuntime](r, order, ptrSize, count)
	case "Effect":
		body, err = ReadT[Effect](r, order, ptrSize, count)
	case "EffectorWeights":
		body, err = ReadT[EffectorWeights](r, order, ptrSize, count)
	case "EnvelopeGpencilModifierData":
		body, err = ReadT[EnvelopeGpencilModifierData](r, order, ptrSize, count)
	case "ExplodeModifierData":
		body, err = ReadT[ExplodeModifierData](r, order, ptrSize, count)
	case "FCM_EnvelopeData":
		body, err = ReadT[FCM_EnvelopeData](r, order, ptrSize, count)
	case "FCurve":
		body, err = ReadT[FCurve](r, order, ptrSize, count)
	case "FFMpegCodecData":
		body, err = ReadT[FFMpegCodecData](r, order, ptrSize, count)
	case "FMod_Cycles":
		body, err = ReadT[FMod_Cycles](r, order, ptrSize, count)
	case "FMod_Envelope":
		body, err = ReadT[FMod_Envelope](r, order, ptrSize, count)
	case "FMod_FunctionGenerator":
		body, err = ReadT[FMod_FunctionGenerator](r, order, ptrSize, count)
	case "FMod_Generator":
		body, err = ReadT[FMod_Generator](r, order, ptrSize, count)
	case "FMod_Limits":
		body, err = ReadT[FMod_Limits](r, order, ptrSize, count)
	case "FMod_Noise":
		body, err = ReadT[FMod_Noise](r, order, ptrSize, count)
	case "FMod_Python":
		body, err = ReadT[FMod_Python](r, order, ptrSize, count)
	case "FMod_Stepped":
		body, err = ReadT[FMod_Stepped](r, order, ptrSize, count)
	case "FModifier":
		body, err = ReadT[FModifier](r, order, ptrSize, count)
	case "FPoint":
		body, err = ReadT[FPoint](r, order, ptrSize, count)
	case "FileAssetSelectParams":
		body, err = ReadT[FileAssetSelectParams](r, order, ptrSize, count)
	case "FileFolderHistory":
		body, err = ReadT[FileFolderHistory](r, order, ptrSize, count)
	case "FileGlobal":
		body, err = ReadT[FileGlobal](r, order, ptrSize, count)
	case "FileSelectParams":
		body, err = ReadT[FileSelectParams](r, order, ptrSize, count)
	case "FlipShaderFxData":
		body, err = ReadT[FlipShaderFxData](r, order, ptrSize, count)
	case "FluidDomainSettings":
		body, err = ReadT[FluidDomainSettings](r, order, ptrSize, count)
	case "FluidEffectorSettings":
		body, err = ReadT[FluidEffectorSettings](r, order, ptrSize, count)
	case "FluidFlowSettings":
		body, err = ReadT[FluidFlowSettings](r, order, ptrSize, count)
	case "FluidModifierData":
		body, err = ReadT[FluidModifierData](r, order, ptrSize, count)
	case "FluidVertexVelocity":
		body, err = ReadT[FluidVertexVelocity](r, order, ptrSize, count)
	case "FluidsimModifierData":
		body, err = ReadT[FluidsimModifierData](r, order, ptrSize, count)
	case "FluidsimSettings":
		body, err = ReadT[FluidsimSettings](r, order, ptrSize, count)
	case "FreestyleConfig":
		body, err = ReadT[FreestyleConfig](r, order, ptrSize, count)
	case "FreestyleEdge":
		body, err = ReadT[FreestyleEdge](r, order, ptrSize, count)
	case "FreestyleFace":
		body, err = ReadT[FreestyleFace](r, order, ptrSize, count)
	case "FreestyleLineSet":
		body, err = ReadT[FreestyleLineSet](r, order, ptrSize, count)
	case "FreestyleLineStyle":
		body, err = ReadT[FreestyleLineStyle](r, order, ptrSize, count)
	case "FreestyleModuleConfig":
		body, err = ReadT[FreestyleModuleConfig](r, order, ptrSize, count)
	case "GPUDOFSettings":
		body, err = ReadT[GPUDOFSettings](r, order, ptrSize, count)
	case "GP_Interpolate_Settings":
		body, err = ReadT[GP_Interpolate_Settings](r, order, ptrSize, count)
	case "GP_Sculpt_Guide":
		body, err = ReadT[GP_Sculpt_Guide](r, order, ptrSize, count)
	case "GP_Sculpt_Settings":
		body, err = ReadT[GP_Sculpt_Settings](r, order, ptrSize, count)
	case "GaussianBlurVars":
		body, err = ReadT[GaussianBlurVars](r, order, ptrSize, count)
	case "GeometryNodeAssetTraits":
		body, err = ReadT[GeometryNodeAssetTraits](r, order, ptrSize, count)
	case "GlowShaderFxData":
		body, err = ReadT[GlowShaderFxData](r, order, ptrSize, count)
	case "GlowVars":
		body, err = ReadT[GlowVars](r, order, ptrSize, count)
	case "GpPaint":
		body, err = ReadT[GpPaint](r, order, ptrSize, count)
	case "GpSculptPaint":
		body, err = ReadT[GpSculptPaint](r, order, ptrSize, count)
	case "GpVertexPaint":
		body, err = ReadT[GpVertexPaint](r, order, ptrSize, count)
	case "GpWeightPaint":
		body, err = ReadT[GpWeightPaint](r, order, ptrSize, count)
	case "GpencilModifierData":
		body, err = ReadT[GpencilModifierData](r, order, ptrSize, count)
	case "GreasePencil":
		body, err = ReadT[GreasePencil](r, order, ptrSize, count)
	case "GreasePencilDrawing":
		body, err = ReadT[GreasePencilDrawing](r, order, ptrSize, count)
	case "GreasePencilDrawingBase":
		body, err = ReadT[GreasePencilDrawingBase](r, order, ptrSize, count)
	case "GreasePencilDrawingReference":
		body, err = ReadT[GreasePencilDrawingReference](r, order, ptrSize, count)
	case "GreasePencilFrame":
		body, err = ReadT[GreasePencilFrame](r, order, ptrSize, count)
	case "GreasePencilLayer":
		body, err = ReadT[GreasePencilLayer](r, order, ptrSize, count)
	case "GreasePencilLayerFramesMapStorage":
		body, err = ReadT[GreasePencilLayerFramesMapStorage](r, order, ptrSize, count)
	case "GreasePencilLayerMask":
		body, err = ReadT[GreasePencilLayerMask](r, order, ptrSize, count)
	case "GreasePencilLayerTreeGroup":
		body, err = ReadT[GreasePencilLayerTreeGroup](r, order, ptrSize, count)
	case "GreasePencilLayerTreeNode":
		body, err = ReadT[GreasePencilLayerTreeNode](r, order, ptrSize, count)
	case "GreasePencilOnionSkinningSettings":
		body, err = ReadT[GreasePencilOnionSkinningSettings](r, order, ptrSize, count)
	case "GridPaintMask":
		body, err = ReadT[GridPaintMask](r, order, ptrSize, count)
	case "GroupNodeViewerPathElem":
		body, err = ReadT[GroupNodeViewerPathElem](r, order, ptrSize, count)
	case "HairKey":
		body, err = ReadT[HairKey](r, order, ptrSize, count)
	case "Histogram":
		body, err = ReadT[Histogram](r, order, ptrSize, count)
	case "HookGpencilModifierData":
		body, err = ReadT[HookGpencilModifierData](r, order, ptrSize, count)
	case "HookModifierData":
		body, err = ReadT[HookModifierData](r, order, ptrSize, count)
	case "HueCorrectModifierData":
		body, err = ReadT[HueCorrectModifierData](r, order, ptrSize, count)
	case "ID":
		body, err = ReadT[ID](r, order, ptrSize, count)
	case "IDOverrideLibrary":
		body, err = ReadT[IDOverrideLibrary](r, order, ptrSize, count)
	case "IDOverrideLibraryProperty":
		body, err = ReadT[IDOverrideLibraryProperty](r, order, ptrSize, count)
	case "IDOverrideLibraryPropertyOperation":
		body, err = ReadT[IDOverrideLibraryPropertyOperation](r, order, ptrSize, count)
	case "IDProperty":
		body, err = ReadT[IDProperty](r, order, ptrSize, count)
	case "IDPropertyData":
		body, err = ReadT[IDPropertyData](r, order, ptrSize, count)
	case "IDPropertyUIData":
		body, err = ReadT[IDPropertyUIData](r, order, ptrSize, count)
	case "IDPropertyUIDataBool":
		body, err = ReadT[IDPropertyUIDataBool](r, order, ptrSize, count)
	case "IDPropertyUIDataFloat":
		body, err = ReadT[IDPropertyUIDataFloat](r, order, ptrSize, count)
	case "IDPropertyUIDataID":
		body, err = ReadT[IDPropertyUIDataID](r, order, ptrSize, count)
	case "IDPropertyUIDataInt":
		body, err = ReadT[IDPropertyUIDataInt](r, order, ptrSize, count)
	case "IDPropertyUIDataString":
		body, err = ReadT[IDPropertyUIDataString](r, order, ptrSize, count)
	case "IDViewerPathElem":
		body, err = ReadT[IDViewerPathElem](r, order, ptrSize, count)
	case "ID_Runtime":
		body, err = ReadT[ID_Runtime](r, order, ptrSize, count)
	case "ID_Runtime_Remap":
		body, err = ReadT[ID_Runtime_Remap](r, order, ptrSize, count)
	case "IdAdtTemplate":
		body, err = ReadT[IdAdtTemplate](r, order, ptrSize, count)
	case "Image":
		body, err = ReadT[Image](r, order, ptrSize, count)
	case "ImageAnim":
		body, err = ReadT[ImageAnim](r, order, ptrSize, count)
	case "ImageFormatData":
		body, err = ReadT[ImageFormatData](r, order, ptrSize, count)
	case "ImagePackedFile":
		body, err = ReadT[ImagePackedFile](r, order, ptrSize, count)
	case "ImagePaintSettings":
		body, err = ReadT[ImagePaintSettings](r, order, ptrSize, count)
	case "ImageTile":
		body, err = ReadT[ImageTile](r, order, ptrSize, count)
	case "ImageTile_Runtime":
		body, err = ReadT[ImageTile_Runtime](r, order, ptrSize, count)
	case "ImageUser":
		body, err = ReadT[ImageUser](r, order, ptrSize, count)
	case "ImageView":
		body, err = ReadT[ImageView](r, order, ptrSize, count)
	case "Image_Runtime":
		body, err = ReadT[Image_Runtime](r, order, ptrSize, count)
	case "Ipo":
		body, err = ReadT[Ipo](r, order, ptrSize, count)
	case "IpoCurve":
		body, err = ReadT[IpoCurve](r, order, ptrSize, count)
	case "IpoDriver":
		body, err = ReadT[IpoDriver](r, order, ptrSize, count)
	case "KS_Path":
		body, err = ReadT[KS_Path](r, order, ptrSize, count)
	case "Key":
		body, err = ReadT[Key](r, order, ptrSize, count)
	case "KeyBlock":
		body, err = ReadT[KeyBlock](r, order, ptrSize, count)
	case "KeyingSet":
		body, err = ReadT[KeyingSet](r, order, ptrSize, count)
	case "Lamp":
		body, err = ReadT[Lamp](r, order, ptrSize, count)
	case "LaplacianDeformModifierData":
		body, err = ReadT[LaplacianDeformModifierData](r, order, ptrSize, count)
	case "LaplacianSmoothModifierData":
		body, err = ReadT[LaplacianSmoothModifierData](r, order, ptrSize, count)
	case "Lattice":
		body, err = ReadT[Lattice](r, order, ptrSize, count)
	case "LatticeGpencilModifierData":
		body, err = ReadT[LatticeGpencilModifierData](r, order, ptrSize, count)
	case "LatticeModifierData":
		body, err = ReadT[LatticeModifierData](r, order, ptrSize, count)
	case "LayerCollection":
		body, err = ReadT[LayerCollection](r, order, ptrSize, count)
	case "LengthGpencilModifierData":
		body, err = ReadT[LengthGpencilModifierData](r, order, ptrSize, count)
	case "Library":
		body, err = ReadT[Library](r, order, ptrSize, count)
	case "LibraryWeakReference":
		body, err = ReadT[LibraryWeakReference](r, order, ptrSize, count)
	case "Library_Runtime":
		body, err = ReadT[Library_Runtime](r, order, ptrSize, count)
	case "LightCache":
		body, err = ReadT[LightCache](r, order, ptrSize, count)
	case "LightCacheTexture":
		body, err = ReadT[LightCacheTexture](r, order, ptrSize, count)
	case "LightGridCache":
		body, err = ReadT[LightGridCache](r, order, ptrSize, count)
	case "LightLinking":
		body, err = ReadT[LightLinking](r, order, ptrSize, count)
	case "LightLinkingRuntime":
		body, err = ReadT[LightLinkingRuntime](r, order, ptrSize, count)
	case "LightProbe":
		body, err = ReadT[LightProbe](r, order, ptrSize, count)
	case "LightProbeBakingData":
		body, err = ReadT[LightProbeBakingData](r, order, ptrSize, count)
	case "LightProbeBlockData":
		body, err = ReadT[LightProbeBlockData](r, order, ptrSize, count)
	case "LightProbeCache":
		body, err = ReadT[LightProbeCache](r, order, ptrSize, count)
	case "LightProbeConnectivityData":
		body, err = ReadT[LightProbeConnectivityData](r, order, ptrSize, count)
	case "LightProbeGridCacheFrame":
		body, err = ReadT[LightProbeGridCacheFrame](r, order, ptrSize, count)
	case "LightProbeIrradianceData":
		body, err = ReadT[LightProbeIrradianceData](r, order, ptrSize, count)
	case "LightProbeObjectCache":
		body, err = ReadT[LightProbeObjectCache](r, order, ptrSize, count)
	case "LightProbeVisibilityData":
		body, err = ReadT[LightProbeVisibilityData](r, order, ptrSize, count)
	case "LightgroupMembership":
		body, err = ReadT[LightgroupMembership](r, order, ptrSize, count)
	case "LineStyleAlphaModifier_AlongStroke":
		body, err = ReadT[LineStyleAlphaModifier_AlongStroke](r, order, ptrSize, count)
	case "LineStyleAlphaModifier_CreaseAngle":
		body, err = ReadT[LineStyleAlphaModifier_CreaseAngle](r, order, ptrSize, count)
	case "LineStyleAlphaModifier_Curvature_3D":
		body, err = ReadT[LineStyleAlphaModifier_Curvature_3D](r, order, ptrSize, count)
	case "LineStyleAlphaModifier_DistanceFromCamera":
		body, err = ReadT[LineStyleAlphaModifier_DistanceFromCamera](r, order, ptrSize, count)
	case "LineStyleAlphaModifier_DistanceFromObject":
		body, err = ReadT[LineStyleAlphaModifier_DistanceFromObject](r, order, ptrSize, count)
	case "LineStyleAlphaModifier_Material":
		body, err = ReadT[LineStyleAlphaModifier_Material](r, order, ptrSize, count)
	case "LineStyleAlphaModifier_Noise":
		body, err = ReadT[LineStyleAlphaModifier_Noise](r, order, ptrSize, count)
	case "LineStyleAlphaModifier_Tangent":
		body, err = ReadT[LineStyleAlphaModifier_Tangent](r, order, ptrSize, count)
	case "LineStyleColorModifier_AlongStroke":
		body, err = ReadT[LineStyleColorModifier_AlongStroke](r, order, ptrSize, count)
	case "LineStyleColorModifier_CreaseAngle":
		body, err = ReadT[LineStyleColorModifier_CreaseAngle](r, order, ptrSize, count)
	case "LineStyleColorModifier_Curvature_3D":
		body, err = ReadT[LineStyleColorModifier_Curvature_3D](r, order, ptrSize, count)
	case "LineStyleColorModifier_DistanceFromCamera":
		body, err = ReadT[LineStyleColorModifier_DistanceFromCamera](r, order, ptrSize, count)
	case "LineStyleColorModifier_DistanceFromObject":
		body, err = ReadT[LineStyleColorModifier_DistanceFromObject](r, order, ptrSize, count)
	case "LineStyleColorModifier_Material":
		body, err = ReadT[LineStyleColorModifier_Material](r, order, ptrSize, count)
	case "LineStyleColorModifier_Noise":
		body, err = ReadT[LineStyleColorModifier_Noise](r, order, ptrSize, count)
	case "LineStyleColorModifier_Tangent":
		body, err = ReadT[LineStyleColorModifier_Tangent](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_2DOffset":
		body, err = ReadT[LineStyleGeometryModifier_2DOffset](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_2DTransform":
		body, err = ReadT[LineStyleGeometryModifier_2DTransform](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_BackboneStretcher":
		body, err = ReadT[LineStyleGeometryModifier_BackboneStretcher](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_BezierCurve":
		body, err = ReadT[LineStyleGeometryModifier_BezierCurve](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_Blueprint":
		body, err = ReadT[LineStyleGeometryModifier_Blueprint](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_GuidingLines":
		body, err = ReadT[LineStyleGeometryModifier_GuidingLines](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_PerlinNoise1D":
		body, err = ReadT[LineStyleGeometryModifier_PerlinNoise1D](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_PerlinNoise2D":
		body, err = ReadT[LineStyleGeometryModifier_PerlinNoise2D](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_Polygonalization":
		body, err = ReadT[LineStyleGeometryModifier_Polygonalization](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_Sampling":
		body, err = ReadT[LineStyleGeometryModifier_Sampling](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_Simplification":
		body, err = ReadT[LineStyleGeometryModifier_Simplification](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_SinusDisplacement":
		body, err = ReadT[LineStyleGeometryModifier_SinusDisplacement](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_SpatialNoise":
		body, err = ReadT[LineStyleGeometryModifier_SpatialNoise](r, order, ptrSize, count)
	case "LineStyleGeometryModifier_TipRemover":
		body, err = ReadT[LineStyleGeometryModifier_TipRemover](r, order, ptrSize, count)
	case "LineStyleModifier":
		body, err = ReadT[LineStyleModifier](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_AlongStroke":
		body, err = ReadT[LineStyleThicknessModifier_AlongStroke](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_Calligraphy":
		body, err = ReadT[LineStyleThicknessModifier_Calligraphy](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_CreaseAngle":
		body, err = ReadT[LineStyleThicknessModifier_CreaseAngle](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_Curvature_3D":
		body, err = ReadT[LineStyleThicknessModifier_Curvature_3D](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_DistanceFromCamera":
		body, err = ReadT[LineStyleThicknessModifier_DistanceFromCamera](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_DistanceFromObject":
		body, err = ReadT[LineStyleThicknessModifier_DistanceFromObject](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_Material":
		body, err = ReadT[LineStyleThicknessModifier_Material](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_Noise":
		body, err = ReadT[LineStyleThicknessModifier_Noise](r, order, ptrSize, count)
	case "LineStyleThicknessModifier_Tangent":
		body, err = ReadT[LineStyleThicknessModifier_Tangent](r, order, ptrSize, count)
	case "LineartGpencilModifierData":
		body, err = ReadT[LineartGpencilModifierData](r, order, ptrSize, count)
	case "Link":
		body, err = ReadT[Link](r, order, ptrSize, count)
	case "LinkData":
		body, err = ReadT[LinkData](r, order, ptrSize, count)
	case "ListBase":
		body, err = ReadT[ListBase](r, order, ptrSize, count)
	case "MBoolProperty":
		body, err = ReadT[MBoolProperty](r, order, ptrSize, count)
	case "MCol":
		body, err = ReadT[MCol](r, order, ptrSize, count)
	case "MDefCell":
		body, err = ReadT[MDefCell](r, order, ptrSize, count)
	case "MDefInfluence":
		body, err = ReadT[MDefInfluence](r, order, ptrSize, count)
	case "MDeformVert":
		body, err = ReadT[MDeformVert](r, order, ptrSize, count)
	case "MDeformWeight":
		body, err = ReadT[MDeformWeight](r, order, ptrSize, count)
	case "MDisps":
		body, err = ReadT[MDisps](r, order, ptrSize, count)
	case "MEdge":
		body, err = ReadT[MEdge](r, order, ptrSize, count)
	case "MFace":
		body, err = ReadT[MFace](r, order, ptrSize, count)
	case "MFloatProperty":
		body, err = ReadT[MFloatProperty](r, order, ptrSize, count)
	case "MInt8Property":
		body, err = ReadT[MInt8Property](r, order, ptrSize, count)
	case "MIntProperty":
		body, err = ReadT[MIntProperty](r, order, ptrSize, count)
	case "MLoop":
		body, err = ReadT[MLoop](r, order, ptrSize, count)
	case "MLoopCol":
		body, err = ReadT[MLoopCol](r, order, ptrSize, count)
	case "MLoopTri":
		body, err = ReadT[MLoopTri](r, order, ptrSize, count)
	case "MLoopUV":
		body, err = ReadT[MLoopUV](r, order, ptrSize, count)
	case "MPoly":
		body, err = ReadT[MPoly](r, order, ptrSize, count)
	case "MPropCol":
		body, err = ReadT[MPropCol](r, order, ptrSize, count)
	case "MRecast":
		body, err = ReadT[MRecast](r, order, ptrSize, count)
	case "MSelect":
		body, err = ReadT[MSelect](r, order, ptrSize, count)
	case "MStringProperty":
		body, err = ReadT[MStringProperty](r, order, ptrSize, count)
	case "MTFace":
		body, err = ReadT[MTFace](r, order, ptrSize, count)
	case "MTex":
		body, err = ReadT[MTex](r, order, ptrSize, count)
	case "MVert":
		body, err = ReadT[MVert](r, order, ptrSize, count)
	case "MVertSkin":
		body, err = ReadT[MVertSkin](r, order, ptrSize, count)
	case "MappingInfoModifierData":
		body, err = ReadT[MappingInfoModifierData](r, order, ptrSize, count)
	case "Mask":
		body, err = ReadT[Mask](r, order, ptrSize, count)
	case "MaskLayer":
		body, err = ReadT[MaskLayer](r, order, ptrSize, count)
	case "MaskLayerShape":
		body, err = ReadT[MaskLayerShape](r, order, ptrSize, count)
	case "MaskModifierData":
		body, err = ReadT[MaskModifierData](r, order, ptrSize, count)
	case "MaskParent":
		body, err = ReadT[MaskParent](r, order, ptrSize, count)
	case "MaskSpaceInfo":
		body, err = ReadT[MaskSpaceInfo](r, order, ptrSize, count)
	case "MaskSpline":
		body, err = ReadT[MaskSpline](r, order, ptrSize, count)
	case "MaskSplinePoint":
		body, err = ReadT[MaskSplinePoint](r, order, ptrSize, count)
	case "MaskSplinePointUW":
		body, err = ReadT[MaskSplinePointUW](r, order, ptrSize, count)
	case "Material":
		body, err = ReadT[Material](r, order, ptrSize, count)
	case "MaterialGPencilStyle":
		body, err = ReadT[MaterialGPencilStyle](r, order, ptrSize, count)
	case "MaterialLineArt":
		body, err = ReadT[MaterialLineArt](r, order, ptrSize, count)
	case "Mesh":
		body, err = ReadT[Mesh](r, order, ptrSize, count)
	case "MeshCacheModifierData":
		body, err = ReadT[MeshCacheModifierData](r, order, ptrSize, count)
	case "MeshDeformModifierData":
		body, err = ReadT[MeshDeformModifierData](r, order, ptrSize, count)
	case "MeshSeqCacheModifierData":
		body, err = ReadT[MeshSeqCacheModifierData](r, order, ptrSize, count)
	case "MeshStatVis":
		body, err = ReadT[MeshStatVis](r, order, ptrSize, count)
	case "MeshToVolumeModifierData":
		body, err = ReadT[MeshToVolumeModifierData](r, order, ptrSize, count)
	case "MetaBall":
		body, err = ReadT[MetaBall](r, order, ptrSize, count)
	case "MetaElem":
		body, err = ReadT[MetaElem](r, order, ptrSize, count)
	case "MetaStack":
		body, err = ReadT[MetaStack](r, order, ptrSize, count)
	case "MirrorGpencilModifierData":
		body, err = ReadT[MirrorGpencilModifierData](r, order, ptrSize, count)
	case "MirrorModifierData":
		body, err = ReadT[MirrorModifierData](r, order, ptrSize, count)
	case "ModifierData":
		body, err = ReadT[ModifierData](r, order, ptrSize, count)
	case "ModifierViewerPathElem":
		body, err = ReadT[ModifierViewerPathElem](r, order, ptrSize, count)
	case "MovieClip":
		body, err = ReadT[MovieClip](r, order, ptrSize, count)
	case "MovieClipProxy":
		body, err = ReadT[MovieClipProxy](r, order, ptrSize, count)
	case "MovieClipScopes":
		body, err = ReadT[MovieClipScopes](r, order, ptrSize, count)
	case "MovieClipUser":
		body, err = ReadT[MovieClipUser](r, order, ptrSize, count)
	case "MovieClip_Runtime":
		body, err = ReadT[MovieClip_Runtime](r, order, ptrSize, count)
	case "MovieClip_RuntimeGPUTexture":
		body, err = ReadT[MovieClip_RuntimeGPUTexture](r, order, ptrSize, count)
	case "MovieReconstructedCamera":
		body, err = ReadT[MovieReconstructedCamera](r, order, ptrSize, count)
	case "MovieTracking":
		body, err = ReadT[MovieTracking](r, order, ptrSize, count)
	case "MovieTrackingCamera":
		body, err = ReadT[MovieTrackingCamera](r, order, ptrSize, count)
	case "MovieTrackingDopesheet":
		body, err = ReadT[MovieTrackingDopesheet](r, order, ptrSize, count)
	case "MovieTrackingDopesheetChannel":
		body, err = ReadT[MovieTrackingDopesheetChannel](r, order, ptrSize, count)
	case "MovieTrackingDopesheetCoverageSegment":
		body, err = ReadT[MovieTrackingDopesheetCoverageSegment](r, order, ptrSize, count)
	case "MovieTrackingMarker":
		body, err = ReadT[MovieTrackingMarker](r, order, ptrSize, count)
	case "MovieTrackingObject":
		body, err = ReadT[MovieTrackingObject](r, order, ptrSize, count)
	case "MovieTrackingPlaneMarker":
		body, err = ReadT[MovieTrackingPlaneMarker](r, order, ptrSize, count)
	case "MovieTrackingPlaneTrack":
		body, err = ReadT[MovieTrackingPlaneTrack](r, order, ptrSize, count)
	case "MovieTrackingReconstruction":
		body, err = ReadT[MovieTrackingReconstruction](r, order, ptrSize, count)
	case "MovieTrackingSettings":
		body, err = ReadT[MovieTrackingSettings](r, order, ptrSize, count)
	case "MovieTrackingStabilization":
		body, err = ReadT[MovieTrackingStabilization](r, order, ptrSize, count)
	case "MovieTrackingStats":
		body, err = ReadT[MovieTrackingStats](r, order, ptrSize, count)
	case "MovieTrackingTrack":
		body, err = ReadT[MovieTrackingTrack](r, order, ptrSize, count)
	case "MultiplyGpencilModifierData":
		body, err = ReadT[MultiplyGpencilModifierData](r, order, ptrSize, count)
	case "MultiresModifierData":
		body, err = ReadT[MultiresModifierData](r, order, ptrSize, count)
	case "NlaStrip":
		body, err = ReadT[NlaStrip](r, order, ptrSize, count)
	case "NlaTrack":
		body, err = ReadT[NlaTrack](r, order, ptrSize, count)
	case "NodeAccumulateField":
		body, err = ReadT[NodeAccumulateField](r, order, ptrSize, count)
	case "NodeAntiAliasingData":
		body, err = ReadT[NodeAntiAliasingData](r, order, ptrSize, count)
	case "NodeBilateralBlurData":
		body, err = ReadT[NodeBilateralBlurData](r, order, ptrSize, count)
	case "NodeBlurData":
		body, err = ReadT[NodeBlurData](r, order, ptrSize, count)
	case "NodeBokehImage":
		body, err = ReadT[NodeBokehImage](r, order, ptrSize, count)
	case "NodeBoxMask":
		body, err = ReadT[NodeBoxMask](r, order, ptrSize, count)
	case "NodeCMPCombSepColor":
		body, err = ReadT[NodeCMPCombSepColor](r, order, ptrSize, count)
	case "NodeChroma":
		body, err = ReadT[NodeChroma](r, order, ptrSize, count)
	case "NodeColorBalance":
		body, err = ReadT[NodeColorBalance](r, order, ptrSize, count)
	case "NodeColorCorrection":
		body, err = ReadT[NodeColorCorrection](r, order, ptrSize, count)
	case "NodeColorspill":
		body, err = ReadT[NodeColorspill](r, order, ptrSize, count)
	case "NodeCombSepColor":
		body, err = ReadT[NodeCombSepColor](r, order, ptrSize, count)
	case "NodeConvertColorSpace":
		body, err = ReadT[NodeConvertColorSpace](r, order, ptrSize, count)
	case "NodeCryptomatte":
		body, err = ReadT[NodeCryptomatte](r, order, ptrSize, count)
	case "NodeCryptomatte_Runtime":
		body, err = ReadT[NodeCryptomatte_Runtime](r, order, ptrSize, count)
	case "NodeDBlurData":
		body, err = ReadT[NodeDBlurData](r, order, ptrSize, count)
	case "NodeDefocus":
		body, err = ReadT[NodeDefocus](r, order, ptrSize, count)
	case "NodeDenoise":
		body, err = ReadT[NodeDenoise](r, order, ptrSize, count)
	case "NodeDilateErode":
		body, err = ReadT[NodeDilateErode](r, order, ptrSize, count)
	case "NodeEllipseMask":
		body, err = ReadT[NodeEllipseMask](r, order, ptrSize, count)
	case "NodeFrame":
		body, err = ReadT[NodeFrame](r, order, ptrSize, count)
	case "NodeFunctionCompare":
		body, err = ReadT[NodeFunctionCompare](r, order, ptrSize, count)
	case "NodeGeometryAttributeCapture":
		body, err = ReadT[NodeGeometryAttributeCapture](r, order, ptrSize, count)
	case "NodeGeometryCollectionInfo":
		body, err = ReadT[NodeGeometryCollectionInfo](r, order, ptrSize, count)
	case "NodeGeometryCurveFill":
		body, err = ReadT[NodeGeometryCurveFill](r, order, ptrSize, count)
	case "NodeGeometryCurveFillet":
		body, err = ReadT[NodeGeometryCurveFillet](r, order, ptrSize, count)
	case "NodeGeometryCurvePrimitiveArc":
		body, err = ReadT[NodeGeometryCurvePrimitiveArc](r, order, ptrSize, count)
	case "NodeGeometryCurvePrimitiveBezierSegment":
		body, err = ReadT[NodeGeometryCurvePrimitiveBezierSegment](r, order, ptrSize, count)
	case "NodeGeometryCurvePrimitiveCircle":
		body, err = ReadT[NodeGeometryCurvePrimitiveCircle](r, order, ptrSize, count)
	case "NodeGeometryCurvePrimitiveLine":
		body, err = ReadT[NodeGeometryCurvePrimitiveLine](r, order, ptrSize, count)
	case "NodeGeometryCurvePrimitiveQuad":
		body, err = ReadT[NodeGeometryCurvePrimitiveQuad](r, order, ptrSize, count)
	case "NodeGeometryCurveResample":
		body, err = ReadT[NodeGeometryCurveResample](r, order, ptrSize, count)
	case "NodeGeometryCurveSample":
		body, err = ReadT[NodeGeometryCurveSample](r, order, ptrSize, count)
	case "NodeGeometryCurveSelectHandles":
		body, err = ReadT[NodeGeometryCurveSelectHandles](r, order, ptrSize, count)
	case "NodeGeometryCurveSetHandles":
		body, err = ReadT[NodeGeometryCurveSetHandles](r, order, ptrSize, count)
	case "NodeGeometryCurveSplineType":
		body, err = ReadT[NodeGeometryCurveSplineType](r, order, ptrSize, count)
	case "NodeGeometryCurveToPoints":
		body, err = ReadT[NodeGeometryCurveToPoints](r, order, ptrSize, count)
	case "NodeGeometryCurveTrim":
		body, err = ReadT[NodeGeometryCurveTrim](r, order, ptrSize, count)
	case "NodeGeometryDeleteGeometry":
		body, err = ReadT[NodeGeometryDeleteGeometry](r, order, ptrSize, count)
	case "NodeGeometryDistributePointsInVolume":
		body, err = ReadT[NodeGeometryDistributePointsInVolume](r, order, ptrSize, count)
	case "NodeGeometryDuplicateElements":
		body, err = ReadT[NodeGeometryDuplicateElements](r, order, ptrSize, count)
	case "NodeGeometryExtrudeMesh":
		body, err = ReadT[NodeGeometryExtrudeMesh](r, order, ptrSize, count)
	case "NodeGeometryImageTexture":
		body, err = ReadT[NodeGeometryImageTexture](r, order, ptrSize, count)
	case "NodeGeometryInputNamedAttribute":
		body, err = ReadT[NodeGeometryInputNamedAttribute](r, order, ptrSize, count)
	case "NodeGeometryMergeByDistance":
		body, err = ReadT[NodeGeometryMergeByDistance](r, order, ptrSize, count)
	case "NodeGeometryMeshCircle":
		body, err = ReadT[NodeGeometryMeshCircle](r, order, ptrSize, count)
	case "NodeGeometryMeshCone":
		body, err = ReadT[NodeGeometryMeshCone](r, order, ptrSize, count)
	case "NodeGeometryMeshCylinder":
		body, err = ReadT[NodeGeometryMeshCylinder](r, order, ptrSize, count)
	case "NodeGeometryMeshLine":
		body, err = ReadT[NodeGeometryMeshLine](r, order, ptrSize, count)
	case "NodeGeometryMeshToPoints":
		body, err = ReadT[NodeGeometryMeshToPoints](r, order, ptrSize, count)
	case "NodeGeometryMeshToVolume":
		body, err = ReadT[NodeGeometryMeshToVolume](r, order, ptrSize, count)
	case "NodeGeometryObjectInfo":
		body, err = ReadT[NodeGeometryObjectInfo](r, order, ptrSize, count)
	case "NodeGeometryPointsToVolume":
		body, err = ReadT[NodeGeometryPointsToVolume](r, order, ptrSize, count)
	case "NodeGeometryProximity":
		body, err = ReadT[NodeGeometryProximity](r, order, ptrSize, count)
	case "NodeGeometryRaycast":
		body, err = ReadT[NodeGeometryRaycast](r, order, ptrSize, count)
	case "NodeGeometryRepeatInput":
		body, err = ReadT[NodeGeometryRepeatInput](r, order, ptrSize, count)
	case "NodeGeometryRepeatOutput":
		body, err = ReadT[NodeGeometryRepeatOutput](r, order, ptrSize, count)
	case "NodeGeometrySampleIndex":
		body, err = ReadT[NodeGeometrySampleIndex](r, order, ptrSize, count)
	case "NodeGeometrySampleVolume":
		body, err = ReadT[NodeGeometrySampleVolume](r, order, ptrSize, count)
	case "NodeGeometrySeparateGeometry":
		body, err = ReadT[NodeGeometrySeparateGeometry](r, order, ptrSize, count)
	case "NodeGeometrySetCurveHandlePositions":
		body, err = ReadT[NodeGeometrySetCurveHandlePositions](r, order, ptrSize, count)
	case "NodeGeometrySimulationInput":
		body, err = ReadT[NodeGeometrySimulationInput](r, order, ptrSize, count)
	case "NodeGeometrySimulationOutput":
		body, err = ReadT[NodeGeometrySimulationOutput](r, order, ptrSize, count)
	case "NodeGeometryStoreNamedAttribute":
		body, err = ReadT[NodeGeometryStoreNamedAttribute](r, order, ptrSize, count)
	case "NodeGeometryStringToCurves":
		body, err = ReadT[NodeGeometryStringToCurves](r, order, ptrSize, count)
	case "NodeGeometrySubdivisionSurface":
		body, err = ReadT[NodeGeometrySubdivisionSurface](r, order, ptrSize, count)
	case "NodeGeometryTransferAttribute":
		body, err = ReadT[NodeGeometryTransferAttribute](r, order, ptrSize, count)
	case "NodeGeometryUVUnwrap":
		body, err = ReadT[NodeGeometryUVUnwrap](r, order, ptrSize, count)
	case "NodeGeometryViewer":
		body, err = ReadT[NodeGeometryViewer](r, order, ptrSize, count)
	case "NodeGeometryVolumeToMesh":
		body, err = ReadT[NodeGeometryVolumeToMesh](r, order, ptrSize, count)
	case "NodeGlare":
		body, err = ReadT[NodeGlare](r, order, ptrSize, count)
	case "NodeHueSat":
		body, err = ReadT[NodeHueSat](r, order, ptrSize, count)
	case "NodeImageAnim":
		body, err = ReadT[NodeImageAnim](r, order, ptrSize, count)
	case "NodeImageFile":
		body, err = ReadT[NodeImageFile](r, order, ptrSize, count)
	case "NodeImageLayer":
		body, err = ReadT[NodeImageLayer](r, order, ptrSize, count)
	case "NodeImageMultiFile":
		body, err = ReadT[NodeImageMultiFile](r, order, ptrSize, count)
	case "NodeImageMultiFileSocket":
		body, err = ReadT[NodeImageMultiFileSocket](r, order, ptrSize, count)
	case "NodeInputBool":
		body, err = ReadT[NodeInputBool](r, order, ptrSize, count)
	case "NodeInputColor":
		body, err = ReadT[NodeInputColor](r, order, ptrSize, count)
	case "NodeInputInt":
		body, err = ReadT[NodeInputInt](r, order, ptrSize, count)
	case "NodeInputString":
		body, err = ReadT[NodeInputString](r, order, ptrSize, count)
	case "NodeInputVector":
		body, err = ReadT[NodeInputVector](r, order, ptrSize, count)
	case "NodeKeyingData":
		body, err = ReadT[NodeKeyingData](r, order, ptrSize, count)
	case "NodeKeyingScreenData":
		body, err = ReadT[NodeKeyingScreenData](r, order, ptrSize, count)
	case "NodeKuwaharaData":
		body, err = ReadT[NodeKuwaharaData](r, order, ptrSize, count)
	case "NodeLensDist":
		body, err = ReadT[NodeLensDist](r, order, ptrSize, count)
	case "NodeMapRange":
		body, err = ReadT[NodeMapRange](r, order, ptrSize, count)
	case "NodeMask":
		body, err = ReadT[NodeMask](r, order, ptrSize, count)
	case "NodePlaneTrackDeformData":
		body, err = ReadT[NodePlaneTrackDeformData](r, order, ptrSize, count)
	case "NodeRandomValue":
		body, err = ReadT[NodeRandomValue](r, order, ptrSize, count)
	case "NodeRepeatItem":
		body, err = ReadT[NodeRepeatItem](r, order, ptrSize, count)
	case "NodeScriptDict":
		body, err = ReadT[NodeScriptDict](r, order, ptrSize, count)
	case "NodeSetAlpha":
		body, err = ReadT[NodeSetAlpha](r, order, ptrSize, count)
	case "NodeShaderAttribute":
		body, err = ReadT[NodeShaderAttribute](r, order, ptrSize, count)
	case "NodeShaderHairPrincipled":
		body, err = ReadT[NodeShaderHairPrincipled](r, order, ptrSize, count)
	case "NodeShaderMix":
		body, err = ReadT[NodeShaderMix](r, order, ptrSize, count)
	case "NodeShaderNormalMap":
		body, err = ReadT[NodeShaderNormalMap](r, order, ptrSize, count)
	case "NodeShaderOutputAOV":
		body, err = ReadT[NodeShaderOutputAOV](r, order, ptrSize, count)
	case "NodeShaderPrincipled":
		body, err = ReadT[NodeShaderPrincipled](r, order, ptrSize, count)
	case "NodeShaderScript":
		body, err = ReadT[NodeShaderScript](r, order, ptrSize, count)
	case "NodeShaderTangent":
		body, err = ReadT[NodeShaderTangent](r, order, ptrSize, count)
	case "NodeShaderTexIES":
		body, err = ReadT[NodeShaderTexIES](r, order, ptrSize, count)
	case "NodeShaderTexPointDensity":
		body, err = ReadT[NodeShaderTexPointDensity](r, order, ptrSize, count)
	case "NodeShaderUVMap":
		body, err = ReadT[NodeShaderUVMap](r, order, ptrSize, count)
	case "NodeShaderVectTransform":
		body, err = ReadT[NodeShaderVectTransform](r, order, ptrSize, count)
	case "NodeShaderVertexColor":
		body, err = ReadT[NodeShaderVertexColor](r, order, ptrSize, count)
	case "NodeSimulationItem":
		body, err = ReadT[NodeSimulationItem](r, order, ptrSize, count)
	case "NodeSunBeams":
		body, err = ReadT[NodeSunBeams](r, order, ptrSize, count)
	case "NodeSwitch":
		body, err = ReadT[NodeSwitch](r, order, ptrSize, count)
	case "NodeTexBase":
		body, err = ReadT[NodeTexBase](r, order, ptrSize, count)
	case "NodeTexBrick":
		body, err = ReadT[NodeTexBrick](r, order, ptrSize, count)
	case "NodeTexChecker":
		body, err = ReadT[NodeTexChecker](r, order, ptrSize, count)
	case "NodeTexEnvironment":
		body, err = ReadT[NodeTexEnvironment](r, order, ptrSize, count)
	case "NodeTexGradient":
		body, err = ReadT[NodeTexGradient](r, order, ptrSize, count)
	case "NodeTexImage":
		body, err = ReadT[NodeTexImage](r, order, ptrSize, count)
	case "NodeTexMagic":
		body, err = ReadT[NodeTexMagic](r, order, ptrSize, count)
	case "NodeTexMusgrave":
		body, err = ReadT[NodeTexMusgrave](r, order, ptrSize, count)
	case "NodeTexNoise":
		body, err = ReadT[NodeTexNoise](r, order, ptrSize, count)
	case "NodeTexSky":
		body, err = ReadT[NodeTexSky](r, order, ptrSize, count)
	case "NodeTexVoronoi":
		body, err = ReadT[NodeTexVoronoi](r, order, ptrSize, count)
	case "NodeTexWave":
		body, err = ReadT[NodeTexWave](r, order, ptrSize, count)
	case "NodeTonemap":
		body, err = ReadT[NodeTonemap](r, order, ptrSize, count)
	case "NodeTrackPosData":
		body, err = ReadT[NodeTrackPosData](r, order, ptrSize, count)
	case "NodeTranslateData":
		body, err = ReadT[NodeTranslateData](r, order, ptrSize, count)
	case "NodeTwoFloats":
		body, err = ReadT[NodeTwoFloats](r, order, ptrSize, count)
	case "NodeTwoXYs":
		body, err = ReadT[NodeTwoXYs](r, order, ptrSize, count)
	case "NodeVertexCol":
		body, err = ReadT[NodeVertexCol](r, order, ptrSize, count)
	case "NodesModifierBake":
		body, err = ReadT[NodesModifierBake](r, order, ptrSize, count)
	case "NodesModifierData":
		body, err = ReadT[NodesModifierData](r, order, ptrSize, count)
	case "NodesModifierSettings":
		body, err = ReadT[NodesModifierSettings](r, order, ptrSize, count)
	case "NoiseGpencilModifierData":
		body, err = ReadT[NoiseGpencilModifierData](r, order, ptrSize, count)
	case "NormalEditModifierData":
		body, err = ReadT[NormalEditModifierData](r, order, ptrSize, count)
	case "Nurb":
		body, err = ReadT[Nurb](r, order, ptrSize, count)
	case "ObHook":
		body, err = ReadT[ObHook](r, order, ptrSize, count)
	case "Object":
		body, err = ReadT[Object](r, order, ptrSize, count)
	case "ObjectLineArt":
		body, err = ReadT[ObjectLineArt](r, order, ptrSize, count)
	case "Object_Runtime":
		body, err = ReadT[Object_Runtime](r, order, ptrSize, count)
	case "OceanModifierData":
		body, err = ReadT[OceanModifierData](r, order, ptrSize, count)
	case "OffsetGpencilModifierData":
		body, err = ReadT[OffsetGpencilModifierData](r, order, ptrSize, count)
	case "OpacityGpencilModifierData":
		body, err = ReadT[OpacityGpencilModifierData](r, order, ptrSize, count)
	case "OutlineGpencilModifierData":
		body, err = ReadT[OutlineGpencilModifierData](r, order, ptrSize, count)
	case "PTCacheExtra":
		body, err = ReadT[PTCacheExtra](r, order, ptrSize, count)
	case "PTCacheMem":
		body, err = ReadT[PTCacheMem](r, order, ptrSize, count)
	case "PackedFile":
		body, err = ReadT[PackedFile](r, order, ptrSize, count)
	case "Paint":
		body, err = ReadT[Paint](r, order, ptrSize, count)
	case "PaintCurve":
		body, err = ReadT[PaintCurve](r, order, ptrSize, count)
	case "PaintCurvePoint":
		body, err = ReadT[PaintCurvePoint](r, order, ptrSize, count)
	case "PaintModeSettings":
		body, err = ReadT[PaintModeSettings](r, order, ptrSize, count)
	case "PaintToolSlot":
		body, err = ReadT[PaintToolSlot](r, order, ptrSize, count)
	case "Paint_Runtime":
		body, err = ReadT[Paint_Runtime](r, order, ptrSize, count)
	case "Palette":
		body, err = ReadT[Palette](r, order, ptrSize, count)
	case "PaletteColor":
		body, err = ReadT[PaletteColor](r, order, ptrSize, count)
	case "Panel":
		body, err = ReadT[Panel](r, order, ptrSize, count)
	case "PanelCategoryStack":
		body, err = ReadT[PanelCategoryStack](r, order, ptrSize, count)
	case "Panel_Runtime":
		body, err = ReadT[Panel_Runtime](r, order, ptrSize, count)
	case "PartDeflect":
		body, err = ReadT[PartDeflect](r, order, ptrSize, count)
	case "PartEff":
		body, err = ReadT[PartEff](r, order, ptrSize, count)
	case "ParticleBrushData":
		body, err = ReadT[ParticleBrushData](r, order, ptrSize, count)
	case "ParticleData":
		body, err = ReadT[ParticleData](r, order, ptrSize, count)
	case "ParticleDupliWeight":
		body, err = ReadT[ParticleDupliWeight](r, order, ptrSize, count)
	case "ParticleEditSettings":
		body, err = ReadT[ParticleEditSettings](r, order, ptrSize, count)
	case "ParticleInstanceModifierData":
		body, err = ReadT[ParticleInstanceModifierData](r, order, ptrSize, count)
	case "ParticleKey":
		body, err = ReadT[ParticleKey](r, order, ptrSize, count)
	case "ParticleSettings":
		body, err = ReadT[ParticleSettings](r, order, ptrSize, count)
	case "ParticleSpring":
		body, err = ReadT[ParticleSpring](r, order, ptrSize, count)
	case "ParticleSystem":
		body, err = ReadT[ParticleSystem](r, order, ptrSize, count)
	case "ParticleSystemModifierData":
		body, err = ReadT[ParticleSystemModifierData](r, order, ptrSize, count)
	case "ParticleTarget":
		body, err = ReadT[ParticleTarget](r, order, ptrSize, count)
	case "PhysicsSettings":
		body, err = ReadT[PhysicsSettings](r, order, ptrSize, count)
	case "PixelShaderFxData":
		body, err = ReadT[PixelShaderFxData](r, order, ptrSize, count)
	case "PointCache":
		body, err = ReadT[PointCache](r, order, ptrSize, count)
	case "PointCloud":
		body, err = ReadT[PointCloud](r, order, ptrSize, count)
	case "PointDensity":
		body, err = ReadT[PointDensity](r, order, ptrSize, count)
	case "PreviewImage":
		body, err = ReadT[PreviewImage](r, order, ptrSize, count)
	case "RaytraceEEVEE":
		body, err = ReadT[RaytraceEEVEE](r, order, ptrSize, count)
	case "RegionAssetShelf":
		body, err = ReadT[RegionAssetShelf](r, order, ptrSize, count)
	case "RegionView3D":
		body, err = ReadT[RegionView3D](r, order, ptrSize, count)
	case "RemeshModifierData":
		body, err = ReadT[RemeshModifierData](r, order, ptrSize, count)
	case "RenderData":
		body, err = ReadT[RenderData](r, order, ptrSize, count)
	case "RenderProfile":
		body, err = ReadT[RenderProfile](r, order, ptrSize, count)
	case "RenderSlot":
		body, err = ReadT[RenderSlot](r, order, ptrSize, count)
	case "RepeatZoneViewerPathElem":
		body, err = ReadT[RepeatZoneViewerPathElem](r, order, ptrSize, count)
	case "ReportList":
		body, err = ReadT[ReportList](r, order, ptrSize, count)
	case "RigidBodyCon":
		body, err = ReadT[RigidBodyCon](r, order, ptrSize, count)
	case "RigidBodyOb":
		body, err = ReadT[RigidBodyOb](r, order, ptrSize, count)
	case "RigidBodyWorld":
		body, err = ReadT[RigidBodyWorld](r, order, ptrSize, count)
	case "RigidBodyWorld_Shared":
		body, err = ReadT[RigidBodyWorld_Shared](r, order, ptrSize, count)
	case "RimShaderFxData":
		body, err = ReadT[RimShaderFxData](r, order, ptrSize, count)
	case "SBVertex":
		body, err = ReadT[SBVertex](r, order, ptrSize, count)
	case "SDefBind":
		body, err = ReadT[SDefBind](r, order, ptrSize, count)
	case "SDefVert":
		body, err = ReadT[SDefVert](r, order, ptrSize, count)
	case "SPHFluidSettings":
		body, err = ReadT[SPHFluidSettings](r, order, ptrSize, count)
	case "Scene":
		body, err = ReadT[Scene](r, order, ptrSize, count)
	case "SceneDisplay":
		body, err = ReadT[SceneDisplay](r, order, ptrSize, count)
	case "SceneEEVEE":
		body, err = ReadT[SceneEEVEE](r, order, ptrSize, count)
	case "SceneGpencil":
		body, err = ReadT[SceneGpencil](r, order, ptrSize, count)
	case "SceneHydra":
		body, err = ReadT[SceneHydra](r, order, ptrSize, count)
	case "SceneRenderLayer":
		body, err = ReadT[SceneRenderLayer](r, order, ptrSize, count)
	case "SceneRenderView":
		body, err = ReadT[SceneRenderView](r, order, ptrSize, count)
	case "Scopes":
		body, err = ReadT[Scopes](r, order, ptrSize, count)
	case "ScrArea":
		body, err = ReadT[ScrArea](r, order, ptrSize, count)
	case "ScrAreaMap":
		body, err = ReadT[ScrAreaMap](r, order, ptrSize, count)
	case "ScrArea_Runtime":
		body, err = ReadT[ScrArea_Runtime](r, order, ptrSize, count)
	case "ScrEdge":
		body, err = ReadT[ScrEdge](r, order, ptrSize, count)
	case "ScrGlobalAreaData":
		body, err = ReadT[ScrGlobalAreaData](r, order, ptrSize, count)
	case "ScrVert":
		body, err = ReadT[ScrVert](r, order, ptrSize, count)
	case "ScrewModifierData":
		body, err = ReadT[ScrewModifierData](r, order, ptrSize, count)
	case "Script":
		body, err = ReadT[Script](r, order, ptrSize, count)
	case "Sculpt":
		body, err = ReadT[Sculpt](r, order, ptrSize, count)
	case "SeqRetimingHandle":
		body, err = ReadT[SeqRetimingHandle](r, order, ptrSize, count)
	case "SeqTimelineChannel":
		body, err = ReadT[SeqTimelineChannel](r, order, ptrSize, count)
	case "Sequence":
		body, err = ReadT[Sequence](r, order, ptrSize, count)
	case "SequenceModifierData":
		body, err = ReadT[SequenceModifierData](r, order, ptrSize, count)
	case "SequenceRuntime":
		body, err = ReadT[SequenceRuntime](r, order, ptrSize, count)
	case "SequencerMaskModifierData":
		body, err = ReadT[SequencerMaskModifierData](r, order, ptrSize, count)
	case "SequencerPreviewOverlay":
		body, err = ReadT[SequencerPreviewOverlay](r, order, ptrSize, count)
	case "SequencerScopes":
		body, err = ReadT[SequencerScopes](r, order, ptrSize, count)
	case "SequencerTimelineOverlay":
		body, err = ReadT[SequencerTimelineOverlay](r, order, ptrSize, count)
	case "SequencerTonemapModifierData":
		body, err = ReadT[SequencerTonemapModifierData](r, order, ptrSize, count)
	case "SequencerToolSettings":
		body, err = ReadT[SequencerToolSettings](r, order, ptrSize, count)
	case "SessionUUID":
		body, err = ReadT[SessionUUID](r, order, ptrSize, count)
	case "ShaderFxData":
		body, err = ReadT[ShaderFxData](r, order, ptrSize, count)
	case "ShaderFxData_Runtime":
		body, err = ReadT[ShaderFxData_Runtime](r, order, ptrSize, count)
	case "ShadowShaderFxData":
		body, err = ReadT[ShadowShaderFxData](r, order, ptrSize, count)
	case "ShapeKeyModifierData":
		body, err = ReadT[ShapeKeyModifierData](r, order, ptrSize, count)
	case "ShrinkwrapGpencilModifierData":
		body, err = ReadT[ShrinkwrapGpencilModifierData](r, order, ptrSize, count)
	case "ShrinkwrapModifierData":
		body, err = ReadT[ShrinkwrapModifierData](r, order, ptrSize, count)
	case "SimpleDeformModifierData":
		body, err = ReadT[SimpleDeformModifierData](r, order, ptrSize, count)
	case "SimplifyGpencilModifierData":
		body, err = ReadT[SimplifyGpencilModifierData](r, order, ptrSize, count)
	case "SimulationZoneViewerPathElem":
		body, err = ReadT[SimulationZoneViewerPathElem](r, order, ptrSize, count)
	case "SkinModifierData":
		body, err = ReadT[SkinModifierData](r, order, ptrSize, count)
	case "SmokeModifierData":
		body, err = ReadT[SmokeModifierData](r, order, ptrSize, count)
	case "SmoothGpencilModifierData":
		body, err = ReadT[SmoothGpencilModifierData](r, order, ptrSize, count)
	case "SmoothModifierData":
		body, err = ReadT[SmoothModifierData](r, order, ptrSize, count)
	case "SoftBody":
		body, err = ReadT[SoftBody](r, order, ptrSize, count)
	case "SoftBody_Shared":
		body, err = ReadT[SoftBody_Shared](r, order, ptrSize, count)
	case "SoftbodyModifierData":
		body, err = ReadT[SoftbodyModifierData](r, order, ptrSize, count)
	case "SolidColorVars":
		body, err = ReadT[SolidColorVars](r, order, ptrSize, count)
	case "SolidLight":
		body, err = ReadT[SolidLight](r, order, ptrSize, count)
	case "SolidifyModifierData":
		body, err = ReadT[SolidifyModifierData](r, order, ptrSize, count)
	case "SoundEqualizerModifierData":
		body, err = ReadT[SoundEqualizerModifierData](r, order, ptrSize, count)
	case "SpaceAction":
		body, err = ReadT[SpaceAction](r, order, ptrSize, count)
	case "SpaceAction_Runtime":
		body, err = ReadT[SpaceAction_Runtime](r, order, ptrSize, count)
	case "SpaceButs":
		body, err = ReadT[SpaceButs](r, order, ptrSize, count)
	case "SpaceClip":
		body, err = ReadT[SpaceClip](r, order, ptrSize, count)
	case "SpaceConsole":
		body, err = ReadT[SpaceConsole](r, order, ptrSize, count)
	case "SpaceFile":
		body, err = ReadT[SpaceFile](r, order, ptrSize, count)
	case "SpaceGraph_Runtime":
		body, err = ReadT[SpaceGraph_Runtime](r, order, ptrSize, count)
	case "SpaceImage":
		body, err = ReadT[SpaceImage](r, order, ptrSize, count)
	case "SpaceImageOverlay":
		body, err = ReadT[SpaceImageOverlay](r, order, ptrSize, count)
	case "SpaceInfo":
		body, err = ReadT[SpaceInfo](r, order, ptrSize, count)
	case "SpaceIpo":
		body, err = ReadT[SpaceIpo](r, order, ptrSize, count)
	case "SpaceLink":
		body, err = ReadT[SpaceLink](r, order, ptrSize, count)
	case "SpaceNla":
		body, err = ReadT[SpaceNla](r, order, ptrSize, count)
	case "SpaceNode":
		body, err = ReadT[SpaceNode](r, order, ptrSize, count)
	case "SpaceNodeOverlay":
		body, err = ReadT[SpaceNodeOverlay](r, order, ptrSize, count)
	case "SpaceOops":
		body, err = ReadT[SpaceOops](r, order, ptrSize, count)
	case "SpaceScript":
		body, err = ReadT[SpaceScript](r, order, ptrSize, count)
	case "SpaceSeq":
		body, err = ReadT[SpaceSeq](r, order, ptrSize, count)
	case "SpaceSeqRuntime":
		body, err = ReadT[SpaceSeqRuntime](r, order, ptrSize, count)
	case "SpaceSpreadsheet":
		body, err = ReadT[SpaceSpreadsheet](r, order, ptrSize, count)
	case "SpaceStatusBar":
		body, err = ReadT[SpaceStatusBar](r, order, ptrSize, count)
	case "SpaceText":
		body, err = ReadT[SpaceText](r, order, ptrSize, count)
	case "SpaceText_Runtime":
		body, err = ReadT[SpaceText_Runtime](r, order, ptrSize, count)
	case "SpaceTopBar":
		body, err = ReadT[SpaceTopBar](r, order, ptrSize, count)
	case "SpaceUserPref":
		body, err = ReadT[SpaceUserPref](r, order, ptrSize, count)
	case "Speaker":
		body, err = ReadT[Speaker](r, order, ptrSize, count)
	case "SpeedControlVars":
		body, err = ReadT[SpeedControlVars](r, order, ptrSize, count)
	case "SpreadsheetColumn":
		body, err = ReadT[SpreadsheetColumn](r, order, ptrSize, count)
	case "SpreadsheetColumnID":
		body, err = ReadT[SpreadsheetColumnID](r, order, ptrSize, count)
	case "SpreadsheetRowFilter":
		body, err = ReadT[SpreadsheetRowFilter](r, order, ptrSize, count)
	case "Stereo3dFormat":
		body, err = ReadT[Stereo3dFormat](r, order, ptrSize, count)
	case "Strip":
		body, err = ReadT[Strip](r, order, ptrSize, count)
	case "StripAnim":
		body, err = ReadT[StripAnim](r, order, ptrSize, count)
	case "StripColorBalance":
		body, err = ReadT[StripColorBalance](r, order, ptrSize, count)
	case "StripCrop":
		body, err = ReadT[StripCrop](r, order, ptrSize, count)
	case "StripElem":
		body, err = ReadT[StripElem](r, order, ptrSize, count)
	case "StripProxy":
		body, err = ReadT[StripProxy](r, order, ptrSize, count)
	case "StripTransform":
		body, err = ReadT[StripTransform](r, order, ptrSize, count)
	case "SubdivGpencilModifierData":
		body, err = ReadT[SubdivGpencilModifierData](r, order, ptrSize, count)
	case "SubsurfModifierData":
		body, err = ReadT[SubsurfModifierData](r, order, ptrSize, count)
	case "SurfaceDeformModifierData":
		body, err = ReadT[SurfaceDeformModifierData](r, order, ptrSize, count)
	case "SurfaceModifierData":
		body, err = ReadT[SurfaceModifierData](r, order, ptrSize, count)
	case "SurfaceModifierData_Runtime":
		body, err = ReadT[SurfaceModifierData_Runtime](r, order, ptrSize, count)
	case "SwirlShaderFxData":
		body, err = ReadT[SwirlShaderFxData](r, order, ptrSize, count)
	case "TFace":
		body, err = ReadT[TFace](r, order, ptrSize, count)
	case "Tex":
		body, err = ReadT[Tex](r, order, ptrSize, count)
	case "TexMapping":
		body, err = ReadT[TexMapping](r, order, ptrSize, count)
	case "TexNodeOutput":
		body, err = ReadT[TexNodeOutput](r, order, ptrSize, count)
	case "TexPaintSlot":
		body, err = ReadT[TexPaintSlot](r, order, ptrSize, count)
	case "Text":
		body, err = ReadT[Text](r, order, ptrSize, count)
	case "TextBox":
		body, err = ReadT[TextBox](r, order, ptrSize, count)
	case "TextLine":
		body, err = ReadT[TextLine](r, order, ptrSize, count)
	case "TextVars":
		body, err = ReadT[TextVars](r, order, ptrSize, count)
	case "TextureGpencilModifierData":
		body, err = ReadT[TextureGpencilModifierData](r, order, ptrSize, count)
	case "ThemeAssetShelf":
		body, err = ReadT[ThemeAssetShelf](r, order, ptrSize, count)
	case "ThemeCollectionColor":
		body, err = ReadT[ThemeCollectionColor](r, order, ptrSize, count)
	case "ThemeSpace":
		body, err = ReadT[ThemeSpace](r, order, ptrSize, count)
	case "ThemeStripColor":
		body, err = ReadT[ThemeStripColor](r, order, ptrSize, count)
	case "ThemeUI":
		body, err = ReadT[ThemeUI](r, order, ptrSize, count)
	case "ThemeWireColor":
		body, err = ReadT[ThemeWireColor](r, order, ptrSize, count)
	case "ThickGpencilModifierData":
		body, err = ReadT[ThickGpencilModifierData](r, order, ptrSize, count)
	case "TimeGpencilModifierData":
		body, err = ReadT[TimeGpencilModifierData](r, order, ptrSize, count)
	case "TimeGpencilModifierSegment":
		body, err = ReadT[TimeGpencilModifierSegment](r, order, ptrSize, count)
	case "TimeMarker":
		body, err = ReadT[TimeMarker](r, order, ptrSize, count)
	case "TintGpencilModifierData":
		body, err = ReadT[TintGpencilModifierData](r, order, ptrSize, count)
	case "ToolSettings":
		body, err = ReadT[ToolSettings](r, order, ptrSize, count)
	case "TransformOrientation":
		body, err = ReadT[TransformOrientation](r, order, ptrSize, count)
	case "TransformOrientationSlot":
		body, err = ReadT[TransformOrientationSlot](r, order, ptrSize, count)
	case "TransformVars":
		body, err = ReadT[TransformVars](r, order, ptrSize, count)
	case "TreeStore":
		body, err = ReadT[TreeStore](r, order, ptrSize, count)
	case "TreeStoreElem":
		body, err = ReadT[TreeStoreElem](r, order, ptrSize, count)
	case "TriangulateModifierData":
		body, err = ReadT[TriangulateModifierData](r, order, ptrSize, count)
	case "UVProjectModifierData":
		body, err = ReadT[UVProjectModifierData](r, order, ptrSize, count)
	case "UVWarpModifierData":
		body, err = ReadT[UVWarpModifierData](r, order, ptrSize, count)
	case "UnifiedPaintSettings":
		body, err = ReadT[UnifiedPaintSettings](r, order, ptrSize, count)
	case "UnitSettings":
		body, err = ReadT[UnitSettings](r, order, ptrSize, count)
	case "UserDef":
		body, err = ReadT[UserDef](r, order, ptrSize, count)
	case "UserDef_Experimental":
		body, err = ReadT[UserDef_Experimental](r, order, ptrSize, count)
	case "UserDef_FileSpaceData":
		body, err = ReadT[UserDef_FileSpaceData](r, order, ptrSize, count)
	case "UserDef_Runtime":
		body, err = ReadT[UserDef_Runtime](r, order, ptrSize, count)
	case "UserDef_SpaceData":
		body, err = ReadT[UserDef_SpaceData](r, order, ptrSize, count)
	case "UvSculpt":
		body, err = ReadT[UvSculpt](r, order, ptrSize, count)
	case "VFont":
		body, err = ReadT[VFont](r, order, ptrSize, count)
	case "VPaint":
		body, err = ReadT[VPaint](r, order, ptrSize, count)
	case "View2D":
		body, err = ReadT[View2D](r, order, ptrSize, count)
	case "View3D":
		body, err = ReadT[View3D](r, order, ptrSize, count)
	case "View3DCursor":
		body, err = ReadT[View3DCursor](r, order, ptrSize, count)
	case "View3DOverlay":
		body, err = ReadT[View3DOverlay](r, order, ptrSize, count)
	case "View3DShading":
		body, err = ReadT[View3DShading](r, order, ptrSize, count)
	case "View3D_Runtime":
		body, err = ReadT[View3D_Runtime](r, order, ptrSize, count)
	case "ViewLayer":
		body, err = ReadT[ViewLayer](r, order, ptrSize, count)
	case "ViewLayerAOV":
		body, err = ReadT[ViewLayerAOV](r, order, ptrSize, count)
	case "ViewLayerEEVEE":
		body, err = ReadT[ViewLayerEEVEE](r, order, ptrSize, count)
	case "ViewLayerEngineData":
		body, err = ReadT[ViewLayerEngineData](r, order, ptrSize, count)
	case "ViewLayerLightgroup":
		body, err = ReadT[ViewLayerLightgroup](r, order, ptrSize, count)
	case "ViewerNodeViewerPathElem":
		body, err = ReadT[ViewerNodeViewerPathElem](r, order, ptrSize, count)
	case "ViewerPath":
		body, err = ReadT[ViewerPath](r, order, ptrSize, count)
	case "ViewerPathElem":
		body, err = ReadT[ViewerPathElem](r, order, ptrSize, count)
	case "Volume":
		body, err = ReadT[Volume](r, order, ptrSize, count)
	case "VolumeDisplaceModifierData":
		body, err = ReadT[VolumeDisplaceModifierData](r, order, ptrSize, count)
	case "VolumeDisplay":
		body, err = ReadT[VolumeDisplay](r, order, ptrSize, count)
	case "VolumeRender":
		body, err = ReadT[VolumeRender](r, order, ptrSize, count)
	case "VolumeToMeshModifierData":
		body, err = ReadT[VolumeToMeshModifierData](r, order, ptrSize, count)
	case "Volume_Runtime":
		body, err = ReadT[Volume_Runtime](r, order, ptrSize, count)
	case "WalkNavigation":
		body, err = ReadT[WalkNavigation](r, order, ptrSize, count)
	case "WarpModifierData":
		body, err = ReadT[WarpModifierData](r, order, ptrSize, count)
	case "WaveEff":
		body, err = ReadT[WaveEff](r, order, ptrSize, count)
	case "WaveModifierData":
		body, err = ReadT[WaveModifierData](r, order, ptrSize, count)
	case "WaveShaderFxData":
		body, err = ReadT[WaveShaderFxData](r, order, ptrSize, count)
	case "WeightAngleGpencilModifierData":
		body, err = ReadT[WeightAngleGpencilModifierData](r, order, ptrSize, count)
	case "WeightProxGpencilModifierData":
		body, err = ReadT[WeightProxGpencilModifierData](r, order, ptrSize, count)
	case "WeightVGEditModifierData":
		body, err = ReadT[WeightVGEditModifierData](r, order, ptrSize, count)
	case "WeightVGMixModifierData":
		body, err = ReadT[WeightVGMixModifierData](r, order, ptrSize, count)
	case "WeightVGProximityModifierData":
		body, err = ReadT[WeightVGProximityModifierData](r, order, ptrSize, count)
	case "WeightedNormalModifierData":
		body, err = ReadT[WeightedNormalModifierData](r, order, ptrSize, count)
	case "WeldModifierData":
		body, err = ReadT[WeldModifierData](r, order, ptrSize, count)
	case "WhiteBalanceModifierData":
		body, err = ReadT[WhiteBalanceModifierData](r, order, ptrSize, count)
	case "WipeVars":
		body, err = ReadT[WipeVars](r, order, ptrSize, count)
	case "WireframeModifierData":
		body, err = ReadT[WireframeModifierData](r, order, ptrSize, count)
	case "WorkSpace":
		body, err = ReadT[WorkSpace](r, order, ptrSize, count)
	case "WorkSpaceDataRelation":
		body, err = ReadT[WorkSpaceDataRelation](r, order, ptrSize, count)
	case "WorkSpaceInstanceHook":
		body, err = ReadT[WorkSpaceInstanceHook](r, order, ptrSize, count)
	case "WorkSpaceLayout":
		body, err = ReadT[WorkSpaceLayout](r, order, ptrSize, count)
	case "World":
		body, err = ReadT[World](r, order, ptrSize, count)
	case "XrActionMap":
		body, err = ReadT[XrActionMap](r, order, ptrSize, count)
	case "XrActionMapBinding":
		body, err = ReadT[XrActionMapBinding](r, order, ptrSize, count)
	case "XrActionMapItem":
		body, err = ReadT[XrActionMapItem](r, order, ptrSize, count)
	case "XrComponentPath":
		body, err = ReadT[XrComponentPath](r, order, ptrSize, count)
	case "XrSessionSettings":
		body, err = ReadT[XrSessionSettings](r, order, ptrSize, count)
	case "XrUserPath":
		body, err = ReadT[XrUserPath](r, order, ptrSize, count)
	case "BAction":
		body, err = ReadT[BAction](r, order, ptrSize, count)
	case "BActionChannel":
		body, err = ReadT[BActionChannel](r, order, ptrSize, count)
	case "BActionConstraint":
		body, err = ReadT[BActionConstraint](r, order, ptrSize, count)
	case "BActionGroup":
		body, err = ReadT[BActionGroup](r, order, ptrSize, count)
	case "BActionModifier":
		body, err = ReadT[BActionModifier](r, order, ptrSize, count)
	case "BActionStrip":
		body, err = ReadT[BActionStrip](r, order, ptrSize, count)
	case "BAddon":
		body, err = ReadT[BAddon](r, order, ptrSize, count)
	case "BAnimVizSettings":
		body, err = ReadT[BAnimVizSettings](r, order, ptrSize, count)
	case "BArmature":
		body, err = ReadT[BArmature](r, order, ptrSize, count)
	case "BArmatureConstraint":
		body, err = ReadT[BArmatureConstraint](r, order, ptrSize, count)
	case "BArmature_Runtime":
		body, err = ReadT[BArmature_Runtime](r, order, ptrSize, count)
	case "BCameraSolverConstraint":
		body, err = ReadT[BCameraSolverConstraint](r, order, ptrSize, count)
	case "BChildOfConstraint":
		body, err = ReadT[BChildOfConstraint](r, order, ptrSize, count)
	case "BClampToConstraint":
		body, err = ReadT[BClampToConstraint](r, order, ptrSize, count)
	case "BConstraint":
		body, err = ReadT[BConstraint](r, order, ptrSize, count)
	case "BConstraintChannel":
		body, err = ReadT[BConstraintChannel](r, order, ptrSize, count)
	case "BConstraintTarget":
		body, err = ReadT[BConstraintTarget](r, order, ptrSize, count)
	case "BDampTrackConstraint":
		body, err = ReadT[BDampTrackConstraint](r, order, ptrSize, count)
	case "BDeformGroup":
		body, err = ReadT[BDeformGroup](r, order, ptrSize, count)
	case "BDistLimitConstraint":
		body, err = ReadT[BDistLimitConstraint](r, order, ptrSize, count)
	case "BDopeSheet":
		body, err = ReadT[BDopeSheet](r, order, ptrSize, count)
	case "BFaceMap":
		body, err = ReadT[BFaceMap](r, order, ptrSize, count)
	case "BFollowPathConstraint":
		body, err = ReadT[BFollowPathConstraint](r, order, ptrSize, count)
	case "BFollowTrackConstraint":
		body, err = ReadT[BFollowTrackConstraint](r, order, ptrSize, count)
	case "BGPDcontrolpoint":
		body, err = ReadT[BGPDcontrolpoint](r, order, ptrSize, count)
	case "BGPDcurve":
		body, err = ReadT[BGPDcurve](r, order, ptrSize, count)
	case "BGPDcurve_point":
		body, err = ReadT[BGPDcurve_point](r, order, ptrSize, count)
	case "BGPDframe":
		body, err = ReadT[BGPDframe](r, order, ptrSize, count)
	case "BGPDframe_Runtime":
		body, err = ReadT[BGPDframe_Runtime](r, order, ptrSize, count)
	case "BGPDlayer":
		body, err = ReadT[BGPDlayer](r, order, ptrSize, count)
	case "BGPDlayer_Mask":
		body, err = ReadT[BGPDlayer_Mask](r, order, ptrSize, count)
	case "BGPDlayer_Runtime":
		body, err = ReadT[BGPDlayer_Runtime](r, order, ptrSize, count)
	case "BGPDpalette":
		body, err = ReadT[BGPDpalette](r, order, ptrSize, count)
	case "BGPDpalettecolor":
		body, err = ReadT[BGPDpalettecolor](r, order, ptrSize, count)
	case "BGPDspoint":
		body, err = ReadT[BGPDspoint](r, order, ptrSize, count)
	case "BGPDspoint_Runtime":
		body, err = ReadT[BGPDspoint_Runtime](r, order, ptrSize, count)
	case "BGPDstroke":
		body, err = ReadT[BGPDstroke](r, order, ptrSize, count)
	case "BGPDstroke_Runtime":
		body, err = ReadT[BGPDstroke_Runtime](r, order, ptrSize, count)
	case "BGPDtriangle":
		body, err = ReadT[BGPDtriangle](r, order, ptrSize, count)
	case "BGPdata":
		body, err = ReadT[BGPdata](r, order, ptrSize, count)
	case "BGPdata_Runtime":
		body, err = ReadT[BGPdata_Runtime](r, order, ptrSize, count)
	case "BGPgrid":
		body, err = ReadT[BGPgrid](r, order, ptrSize, count)
	case "BIKParam":
		body, err = ReadT[BIKParam](r, order, ptrSize, count)
	case "BItasc":
		body, err = ReadT[BItasc](r, order, ptrSize, count)
	case "BKinematicConstraint":
		body, err = ReadT[BKinematicConstraint](r, order, ptrSize, count)
	case "BLocLimitConstraint":
		body, err = ReadT[BLocLimitConstraint](r, order, ptrSize, count)
	case "BLocateLikeConstraint":
		body, err = ReadT[BLocateLikeConstraint](r, order, ptrSize, count)
	case "BLockTrackConstraint":
		body, err = ReadT[BLockTrackConstraint](r, order, ptrSize, count)
	case "BMinMaxConstraint":
		body, err = ReadT[BMinMaxConstraint](r, order, ptrSize, count)
	case "BMotionPath":
		body, err = ReadT[BMotionPath](r, order, ptrSize, count)
	case "BMotionPathVert":
		body, err = ReadT[BMotionPathVert](r, order, ptrSize, count)
	case "BNestedNodePath":
		body, err = ReadT[BNestedNodePath](r, order, ptrSize, count)
	case "BNestedNodeRef":
		body, err = ReadT[BNestedNodeRef](r, order, ptrSize, count)
	case "BNode":
		body, err = ReadT[BNode](r, order, ptrSize, count)
	case "BNodeInstanceKey":
		body, err = ReadT[BNodeInstanceKey](r, order, ptrSize, count)
	case "BNodeLink":
		body, err = ReadT[BNodeLink](r, order, ptrSize, count)
	case "BNodePanelState":
		body, err = ReadT[BNodePanelState](r, order, ptrSize, count)
	case "BNodeSocket":
		body, err = ReadT[BNodeSocket](r, order, ptrSize, count)
	case "BNodeSocketValueBoolean":
		body, err = ReadT[BNodeSocketValueBoolean](r, order, ptrSize, count)
	case "BNodeSocketValueCollection":
		body, err = ReadT[BNodeSocketValueCollection](r, order, ptrSize, count)
	case "BNodeSocketValueFloat":
		body, err = ReadT[BNodeSocketValueFloat](r, order, ptrSize, count)
	case "BNodeSocketValueImage":
		body, err = ReadT[BNodeSocketValueImage](r, order, ptrSize, count)
	case "BNodeSocketValueInt":
		body, err = ReadT[BNodeSocketValueInt](r, order, ptrSize, count)
	case "BNodeSocketValueMaterial":
		body, err = ReadT[BNodeSocketValueMaterial](r, order, ptrSize, count)
	case "BNodeSocketValueObject":
		body, err = ReadT[BNodeSocketValueObject](r, order, ptrSize, count)
	case "BNodeSocketValueRGBA":
		body, err = ReadT[BNodeSocketValueRGBA](r, order, ptrSize, count)
	case "BNodeSocketValueRotation":
		body, err = ReadT[BNodeSocketValueRotation](r, order, ptrSize, count)
	case "BNodeSocketValueString":
		body, err = ReadT[BNodeSocketValueString](r, order, ptrSize, count)
	case "BNodeSocketValueTexture":
		body, err = ReadT[BNodeSocketValueTexture](r, order, ptrSize, count)
	case "BNodeSocketValueVector":
		body, err = ReadT[BNodeSocketValueVector](r, order, ptrSize, count)
	case "BNodeStack":
		body, err = ReadT[BNodeStack](r, order, ptrSize, count)
	case "BNodeTree":
		body, err = ReadT[BNodeTree](r, order, ptrSize, count)
	case "BNodeTreeInterface":
		body, err = ReadT[BNodeTreeInterface](r, order, ptrSize, count)
	case "BNodeTreeInterfaceItem":
		body, err = ReadT[BNodeTreeInterfaceItem](r, order, ptrSize, count)
	case "BNodeTreeInterfacePanel":
		body, err = ReadT[BNodeTreeInterfacePanel](r, order, ptrSize, count)
	case "BNodeTreeInterfaceSocket":
		body, err = ReadT[BNodeTreeInterfaceSocket](r, order, ptrSize, count)
	case "BNodeTreePath":
		body, err = ReadT[BNodeTreePath](r, order, ptrSize, count)
	case "BObjectSolverConstraint":
		body, err = ReadT[BObjectSolverConstraint](r, order, ptrSize, count)
	case "BPathCompare":
		body, err = ReadT[BPathCompare](r, order, ptrSize, count)
	case "BPivotConstraint":
		body, err = ReadT[BPivotConstraint](r, order, ptrSize, count)
	case "BPose":
		body, err = ReadT[BPose](r, order, ptrSize, count)
	case "BPoseChannel":
		body, err = ReadT[BPoseChannel](r, order, ptrSize, count)
	case "BPoseChannel_BBoneSegmentBoundary":
		body, err = ReadT[BPoseChannel_BBoneSegmentBoundary](r, order, ptrSize, count)
	case "BPoseChannel_Runtime":
		body, err = ReadT[BPoseChannel_Runtime](r, order, ptrSize, count)
	case "BPythonConstraint":
		body, err = ReadT[BPythonConstraint](r, order, ptrSize, count)
	case "BRigidBodyJointConstraint":
		body, err = ReadT[BRigidBodyJointConstraint](r, order, ptrSize, count)
	case "BRotLimitConstraint":
		body, err = ReadT[BRotLimitConstraint](r, order, ptrSize, count)
	case "BRotateLikeConstraint":
		body, err = ReadT[BRotateLikeConstraint](r, order, ptrSize, count)
	case "BSameVolumeConstraint":
		body, err = ReadT[BSameVolumeConstraint](r, order, ptrSize, count)
	case "BScreen":
		body, err = ReadT[BScreen](r, order, ptrSize, count)
	case "BShrinkwrapConstraint":
		body, err = ReadT[BShrinkwrapConstraint](r, order, ptrSize, count)
	case "BSizeLikeConstraint":
		body, err = ReadT[BSizeLikeConstraint](r, order, ptrSize, count)
	case "BSizeLimitConstraint":
		body, err = ReadT[BSizeLimitConstraint](r, order, ptrSize, count)
	case "BSound":
		body, err = ReadT[BSound](r, order, ptrSize, count)
	case "BSplineIKConstraint":
		body, err = ReadT[BSplineIKConstraint](r, order, ptrSize, count)
	case "BStretchToConstraint":
		body, err = ReadT[BStretchToConstraint](r, order, ptrSize, count)
	case "BTheme":
		body, err = ReadT[BTheme](r, order, ptrSize, count)
	case "BToolRef":
		body, err = ReadT[BToolRef](r, order, ptrSize, count)
	case "BTrackToConstraint":
		body, err = ReadT[BTrackToConstraint](r, order, ptrSize, count)
	case "BTransLikeConstraint":
		body, err = ReadT[BTransLikeConstraint](r, order, ptrSize, count)
	case "BTransformCacheConstraint":
		body, err = ReadT[BTransformCacheConstraint](r, order, ptrSize, count)
	case "BTransformConstraint":
		body, err = ReadT[BTransformConstraint](r, order, ptrSize, count)
	case "BUUID":
		body, err = ReadT[BUUID](r, order, ptrSize, count)
	case "BUserAssetLibrary":
		body, err = ReadT[BUserAssetLibrary](r, order, ptrSize, count)
	case "BUserExtensionRepo":
		body, err = ReadT[BUserExtensionRepo](r, order, ptrSize, count)
	case "BUserMenu":
		body, err = ReadT[BUserMenu](r, order, ptrSize, count)
	case "BUserMenuItem":
		body, err = ReadT[BUserMenuItem](r, order, ptrSize, count)
	case "BUserMenuItem_Menu":
		body, err = ReadT[BUserMenuItem_Menu](r, order, ptrSize, count)
	case "BUserMenuItem_Op":
		body, err = ReadT[BUserMenuItem_Op](r, order, ptrSize, count)
	case "BUserMenuItem_Prop":
		body, err = ReadT[BUserMenuItem_Prop](r, order, ptrSize, count)
	case "BUserScriptDirectory":
		body, err = ReadT[BUserScriptDirectory](r, order, ptrSize, count)
	case "Rctf":
		body, err = ReadT[Rctf](r, order, ptrSize, count)
	case "Rcti":
		body, err = ReadT[Rcti](r, order, ptrSize, count)
	case "TPaletteColorHSV":
		body, err = ReadT[TPaletteColorHSV](r, order, ptrSize, count)
	case "UiFontStyle":
		body, err = ReadT[UiFontStyle](r, order, ptrSize, count)
	case "UiList":
		body, err = ReadT[UiList](r, order, ptrSize, count)
	case "UiPanelColors":
		body, err = ReadT[UiPanelColors](r, order, ptrSize, count)
	case "UiPreview":
		body, err = ReadT[UiPreview](r, order, ptrSize, count)
	case "UiStyle":
		body, err = ReadT[UiStyle](r, order, ptrSize, count)
	case "UiWidgetColors":
		body, err = ReadT[UiWidgetColors](r, order, ptrSize, count)
	case "UiWidgetStateColors":
		body, err = ReadT[UiWidgetStateColors](r, order, ptrSize, count)
	case "Vec2f":
		body, err = ReadT[Vec2f](r, order, ptrSize, count)
	case "Vec2i":
		body, err = ReadT[Vec2i](r, order, ptrSize, count)
	case "Vec2s":
		body, err = ReadT[Vec2s](r, order, ptrSize, count)
	case "Vec3f":
		body, err = ReadT[Vec3f](r, order, ptrSize, count)
	case "Vec4f":
		body, err = ReadT[Vec4f](r, order, ptrSize, count)
	case "WmKeyConfig":
		body, err = ReadT[WmKeyConfig](r, order, ptrSize, count)
	case "WmKeyConfigPref":
		body, err = ReadT[WmKeyConfigPref](r, order, ptrSize, count)
	case "WmKeyMap":
		body, err = ReadT[WmKeyMap](r, order, ptrSize, count)
	case "WmKeyMapDiffItem":
		body, err = ReadT[WmKeyMapDiffItem](r, order, ptrSize, count)
	case "WmKeyMapItem":
		body, err = ReadT[WmKeyMapItem](r, order, ptrSize, count)
	case "WmOperator":
		body, err = ReadT[WmOperator](r, order, ptrSize, count)
	case "WmOwnerID":
		body, err = ReadT[WmOwnerID](r, order, ptrSize, count)
	case "WmWindow":
		body, err = ReadT[WmWindow](r, order, ptrSize, count)
	case "WmWindowManager":
		body, err = ReadT[WmWindowManager](r, order, ptrSize, count)
	case "WmXrData":
		body, err = ReadT[WmXrData](r, order, ptrSize, count)
	}
 
	if err != nil {
		return nil, err
	}
	
	return body, EnsureAllRead(r, typ)
}